spring:
  application:
    name: library_management

  datasource:
    url: jdbc:mysql://localhost:3306/library_management
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    openai:
      api-key: ${GROQ_KEY}
      base-url:  https://api.groq.com/openai/v1
      chat:
        options:
          model: llama-3.3-70b-versatile

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

server:
  tomcat:
    max-part-count: 50
  servlet:
    context-path: /qltv
    port: 8080

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}